Repository SpiNNakerManchester/PACMAN, pull requests merged in 2019-07, with the labels that each got.

#206 reimplented get_max_atoms_per_core
  pacman/model/graphs/application/application_vertex.py
  pacman/operations/partition_algorithms/partition_and_place_partitioner.py
Labels: bug

#218 Spreader placer
  pacman/operations/algorithms_metadata.xml
  pacman/operations/placer_algorithms/__init__.py
  pacman/operations/placer_algorithms/one_to_one_placer.py
  pacman/operations/placer_algorithms/spreader_placer.py
  pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
  unittests/operations_tests/placer_algorithms_tests/test_same_chip_constraint.py
  unittests/operations_tests/placer_algorithms_tests/test_sdram_edge_placement.py
  unittests/operations_tests/placer_algorithms_tests/test_spreader_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_virtual_placement.py
Labels: enhancement

#220 Compression2
  pacman/operations/algorithm_reports/reports.py
  pacman/operations/algorithm_reports/reports_metadata.xml
  pacman/operations/algorithm_reports/routing_compression_checker_report.py
  pacman/operations/algorithms_metadata.xml
  pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
  pacman/operations/routing_table_generators/basic_routing_table_generator.py
  pacman/operations/routing_table_generators/zoned_routing_table_generator.py
Labels: enhancement

#237 Rename misspelt report
  pacman/operations/algorithm_reports/reports_metadata.xml
Labels: minor
