Repository SpiNNakerManchester/PACMAN, pull requests merged in 2019-08, with the labels that each got.

#231 Better bit counting
  pacman/operations/rigged_algorithms/hilbert_placer.py
  pacman/operations/router_compressors/malloc_based_route_merger.py
  pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/utils.py
Labels: enhancement, minor

#234 added or updated classifiers
  setup.py
Labels: enhancement

#238 Minor spelling mistake
  pacman/utilities/utility_objs/resource_tracker.py
Labels: minor

#239 total_compressed
  pacman/operations/algorithm_reports/reports.py
Labels: enhancement, minor

#242 5.0.1
  pacman/_version.py
  requirements.txt
  setup.py
Labels: enhancement

#243 fix to stop nothing to report causeing divide by zero
  pacman/operations/algorithm_reports/reports.py
Labels: bug

#245 Fix the divide by zero problem for real this time
  pacman/operations/algorithm_reports/reports.py
Labels: BLOCKER!, bug

#254 connective based placer is dead and needs a burial
  pacman/operations/placer_algorithms/__init__.py
  pacman/operations/placer_algorithms/connective_based_placer.py
Labels: bug

#253 index not needed
  pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
Labels: enhancement

#252 Nuke ugly hacks
  pacman/utilities/file_format_converters/__init__.py
  pacman/utilities/file_format_converters/convert_to_file_core_allocations.py
  pacman/utilities/file_format_converters/convert_to_file_machine.py
  pacman/utilities/file_format_converters/convert_to_file_machine_graph.py
  pacman/utilities/file_format_converters/convert_to_file_machine_graph_pure_multicast.py
  pacman/utilities/file_format_converters/convert_to_file_placement.py
  pacman/utilities/file_format_converters/convert_to_memory_multi_cast_routes.py
  pacman/utilities/file_format_converters/convert_to_memory_placements.py
  pacman/utilities/file_format_converters/converter_algorithms_metadata.xml
  pacman/utilities/file_format_converters/create_file_constraints.py
  pacman/utilities/file_format_schemas/constraints.json
  pacman/utilities/file_format_schemas/core_allocations.json
  pacman/utilities/file_format_schemas/machine.json
  pacman/utilities/file_format_schemas/machine_graph.json
  pacman/utilities/file_format_schemas/placements.json
  unittests/utilities_tests/test_format_converters.py
Labels: enhancement

#255 router clock speed was wrong and unused so hammer applied
  pacman/utilities/algorithm_utilities/machine_algorithm_utilities.py
  unittests/operations_tests/partition_algorithms_tests/test_basic_partitioner.py
  unittests/operations_tests/partition_algorithms_tests/test_partition_and_place_partitioner.py
  unittests/operations_tests/placer_algorithms_tests/test_basic_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_radial_placer.py
Labels: bug

#247 Diamonds are not forever
  pacman/model/constraints/router_constraints/abstract_router_constraint.py
  pacman/model/graphs/__init__.py
  pacman/model/graphs/abstract_fpga.py
  pacman/model/graphs/abstract_spinnaker_link.py
  pacman/model/graphs/abstract_spinnaker_link_vertex.py
  pacman/model/graphs/abstract_virtual.py
  pacman/model/graphs/application/application_fpga_vertex.py
  pacman/model/graphs/application/application_spinnaker_link_vertex.py
  pacman/model/graphs/machine/machine_fpga_vertex.py
  pacman/model/graphs/machine/machine_spinnaker_link_vertex.py
  pacman/operations/algorithm_reports/reports.py
  pacman/operations/chip_id_allocator_algorithms/malloc_based_chip_id_allocator.py
  pacman/operations/partition_algorithms/partition_and_place_partitioner.py
  pacman/operations/placer_algorithms/one_to_one_placer.py
  pacman/operations/router_algorithms/ner_route.py
  pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
Labels: enhancement
