Repository SpiNNakerManchester/PACMAN, pull requests merged in 2019-04, with the labels that each got.

#204 Fix radial placer to use constraints properly
  pacman/operations/placer_algorithms/one_to_one_placer.py
  pacman/operations/placer_algorithms/radial_placer.py
  pacman/utilities/utility_objs/resource_tracker.py
Labels: bug

#189 Structural plasticity
  pacman/utilities/utility_calls.py
Labels: minor

#208 Order
  pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
  pacman/utilities/algorithm_utilities/routing_info_allocator_utilities.py
Labels: enhancement

#195 removed an n * n * n problems with large one to one chains
  pacman/operations/placer_algorithms/one_to_one_placer.py
  pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
  unittests/utilities_tests/test_placer_algorithm_utilities.py
Labels: BLOCKER!, bug
