Repository SpiNNakerManchester/PACMAN, pull requests merged in 2019-10, with the labels that each got.

#262 Pylint
  .pylintrc
  .travis.yml
  pacman/exceptions.py
  pacman/executor/algorithm_decorators/algorithm_decorator.py
  pacman/executor/algorithm_metadata_xml_reader.py
  pacman/executor/injection_decorator.py
  pacman/executor/pacman_algorithm_executor.py
  pacman/model/graphs/abstract_fpga.py
  pacman/model/graphs/abstract_spinnaker_link.py
  pacman/model/graphs/common/constrained_object.py
  pacman/model/resources/__init__.py
  pacman/model/resources/resource_container.py
  pacman/operations/algorithm_reports/convert_to_json_machine_graph.py
  pacman/operations/algorithms_metadata.xml
  pacman/operations/fixed_route_router/fixed_route_router.py
  pacman/operations/multi_cast_router_check_functionality/valid_routes_checker.py
  pacman/operations/placer_algorithms/spreader_placer.py
  pacman/operations/router_algorithms/basic_dijkstra_routing.py
  pacman/operations/router_algorithms/routing_tree.py
  pacman/operations/router_compressors/abstract_compressor.py
  pacman/operations/router_compressors/clash_compressor.py
  pacman/operations/router_compressors/malloc_based_route_merger.py
  pacman/operations/router_compressors/mundys_router_compressor/ordered_covering.py
  pacman/operations/router_compressors/mundys_router_compressor/remove_default_routes.py
  pacman/operations/router_compressors/mundys_router_compressor/routing_table_condenser.py
  pacman/operations/router_compressors/pair_compressor.py
  pacman/operations/router_compressors/unordered_compressor.py
  pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/compressible_malloc_based_routing_info_allocator.py
  pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/key_field_generator.py
  pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
  pacman/utilities/algorithm_utilities/field_based_system_utilities.py
  pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
  pacman/utilities/json_utils.py
  pacman/utilities/utility_calls.py
  pacman/utilities/utility_objs/flexi_field.py
  pacman/utilities/utility_objs/resource_tracker.py
  requirements-test.txt
  unittests/test_fixed_route_router.py
Labels: enhancement, minor

#263 fixed incorrect import from collections.abc
  pacman/executor/injection_decorator.py
  pacman/executor/pacman_algorithm_executor.py
  pacman/model/graphs/impl/graph.py
  pacman/model/placements/placements.py
  pacman/model/routing_table_by_partition/multicast_routing_table_by_partition.py
  pacman/model/routing_tables/multicast_routing_table.py
  pacman/model/routing_tables/multicast_routing_tables.py
  pacman/model/tags/tags.py
  pacman/operations/algorithm_reports/routing_compression_checker_report.py
  pacman/operations/multi_cast_router_check_functionality/valid_routes_checker.py
  pacman/operations/placer_algorithms/radial_placer.py
  pacman/operations/router_compressors/clash_compressor.py
  pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/compressible_malloc_based_routing_info_allocator.py
  pacman/utilities/algorithm_utilities/partition_algorithm_utilities.py
  pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
  pacman/utilities/algorithm_utilities/routing_info_allocator_utilities.py
  pacman/utilities/json_utils.py
  pacman/utilities/utility_objs/resource_tracker.py
  setup.py
  unittests/operations_tests/router_algorithms_tests/test_basic_dijkstra_routing.py
  unittests/operations_tests/tag_allocator_tests/test_tags_board_addresses.py
Labels: bug

#264 Stabilise the JSON test code
  unittests/utilities_tests/test_json_utils.py
Labels: bug, minor

#261 Make vertices set again
  pacman/model/graphs/impl/graph.py
Labels: enhancement

#266 Fix docs
  .travis.yml
  doc/source/.gitignore
  doc/source/conf.py
  doc/source/index.rst
  pacman/exceptions.py
  pacman/model/graphs/abstract_vertex.py
  pacman/model/resources/abstract_sdram.py
  pacman/operations/algorithm_reports/reports.py
  pacman/operations/router_algorithms/routing_tree.py
  pacman/operations/router_compressors/abstract_compressor.py
  pacman/operations/router_compressors/mundys_router_compressor/ordered_covering.py
  pacman/operations/router_compressors/mundys_router_compressor/remove_default_routes.py
  pacman/operations/router_compressors/mundys_router_compressor/utils.py
  pacman/operations/router_compressors/pair_compressor.py
Labels: enhancement, minor
