Repository SpiNNakerManchester/PACMAN, pull requests merged in 2020-08, with the labels that each got.

#303 Add testing with Python 3.8
  .travis.yml
  setup.py
Labels: enhancement, minor

#299 Pre filter
  pacman/model/partitioner_interfaces/__init__.py
  pacman/model/partitioner_interfaces/abstract_slices_connect.py
  pacman/utilities/algorithm_utilities/partition_algorithm_utilities.py
Labels: enhancement

#304 Moved get_n_keys_for_partition to MachineVertex
  pacman/model/graphs/machine/machine_vertex.py
Labels: enhancement

#305 Bring back connective placer
  pacman/operations/placer_algorithms/__init__.py
  pacman/operations/placer_algorithms/connective_based_placer.py
  uinit_test_objects/placer_test_support.py
  unittests/operations_tests/placer_algorithms_tests/test_connecitve_placer.py
Labels: SHOULD NEVER HAVE BEEN REMOVED!, enhancement
