Repository SpiNNakerManchester/PACMAN, pull requests merged in 2020-12, with the labels that each got.

#337 Version binding for numpy
  doc/source/conf.py
  requirements.txt
  setup.py
Labels: BLOCKER!, bug

#336 fix PACMANAlgorithmExecutor.__find_suitable_algorithm error message
  pacman/executor/pacman_algorithm_executor.py
  pacman/executor/token_states.py
  pacman/model/partitioner_splitters/splitter_one_app_one_machine.py
  unittests/model_tests/splitter_tests/__init__.py
  unittests/model_tests/splitter_tests/test_one_app_one_machine.py
  unittests/model_tests/splitter_tests/test_splitter_slice_legacy.py
  unittests/test_token_states.py
Labels: bug

#339 Corrections to numpy version requirements
  requirements.txt
  setup.py
Labels: BLOCKER!, bug

#340 get_placement_on_processor
  pacman/model/placements/placements.py
  pacman/operations/router_compressors/pair_compressor.py
  unittests/model_tests/placement_tests/test_placements_model.py
Labels: enhancement
