Repository SpiNNakerManchester/PACMAN, pull requests merged in 2020-11, with the labels that each got.

#317 refactored get vertices methods so they are the same name as slice ones
  pacman/model/partitioner_splitters/abstract_splitters/abstract_splitter_common.py
  pacman/model/partitioner_splitters/abstract_splitters/abstract_splitter_slice.py
  pacman/model/partitioner_splitters/splitter_one_app_one_machine.py
  pacman/model/partitioner_splitters/splitter_one_to_one_legacy.py
  pacman/operations/partition_algorithms/splitter_partitioner.py
Labels: enhancement

#324 turn on python actions
  .github/workflows/python_actions.yml
  .ratexcludes
  doc/source/conf.py
  pacman/model/graphs/application/application_edge.py
  pacman/model/resources/abstract_sdram.py
  pacman/model/resources/constant_sdram.py
  pacman/model/resources/cpu_cycles_per_tick_resource.py
  pacman/model/resources/multi_region_sdram.py
  pacman/model/routing_tables/__init__.py
  pacman/model/routing_tables/abstract_multicast_routing_table.py
  pacman/model/routing_tables/compressed_multicast_routing_table.py
  pacman/model/routing_tables/uncompressed_multicast_routing_table.py
  pacman/operations/algorithm_reports/reports.py
  pacman/operations/algorithm_reports/write_json_machine_graph.py
  pacman/operations/routing_info_allocator_algorithms/destination_based_key_allocator.py
  pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
  pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
  requirements-test.txt
  requirements.txt
Labels: BLOCKER!, enhancement

#325 Fix Python documentation
  doc/source/conf.py
  pacman/model/graphs/application/application_edge.py
  pacman/model/resources/abstract_sdram.py
  pacman/model/resources/constant_sdram.py
  pacman/model/resources/cpu_cycles_per_tick_resource.py
  pacman/model/resources/multi_region_sdram.py
  pacman/model/routing_tables/__init__.py
  pacman/model/routing_tables/abstract_multicast_routing_table.py
  pacman/model/routing_tables/compressed_multicast_routing_table.py
  pacman/model/routing_tables/uncompressed_multicast_routing_table.py
  pacman/operations/algorithm_reports/reports.py
  pacman/operations/algorithm_reports/write_json_machine_graph.py
  pacman/operations/routing_info_allocator_algorithms/destination_based_key_allocator.py
  pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
  pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
Labels: BLOCKER!, bug, enhancement

#310 Disable same atoms as vertex
  pacman/model/constraints/partitioner_constraints/same_atoms_as_vertex_constraint.py
  pacman/model/graphs/common/slice.py
  pacman/model/partitioner_splitters/splitter_slice_legacy.py
  pacman/operations/partition_algorithms/splitter_partitioner.py
  unittests/model_tests/test_partition.py
  unittests/operations_tests/partition_algorithms_tests/test_partition_and_place_partitioner.py
  unittests/utilities_tests/test_json_utils.py
Labels: enhancement

#328 Cb sdram
  pacman/model/graphs/__init__.py
  pacman/model/graphs/abstract_sdram_multiple_partition.py
  pacman/model/graphs/abstract_sdram_single_partition.py
  pacman/model/graphs/application/application_graph.py
  pacman/model/graphs/graph.py
  pacman/model/graphs/machine/__init__.py
  pacman/model/graphs/machine/abstract_sdram_partition.py
  pacman/model/graphs/machine/constant_sdram_machine_partition.py
  pacman/model/graphs/machine/destination_segmented_sdram_machine_partition.py
  pacman/model/graphs/machine/machine_graph.py
  pacman/model/graphs/machine/source_segmented_sdram_machine_partition.py
  pacman/operations/partition_algorithms/splitter_partitioner.py
  pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
Labels: enhancement

#329 block attempt to add edges to partitions outside of graph
  pacman/model/graphs/graph.py
  pacman/model/graphs/outgoing_edge_partition.py
  unittests/model_tests/routing_info_tests/test_routing_info.py
Labels: enhancement

#323 Application Vertices should make sure n_atoms is an int
  pacman/model/graphs/application/application_fpga_vertex.py
  pacman/model/graphs/application/application_spinnaker_link_vertex.py
  pacman/model/graphs/application/application_vertex.py
  uinit_test_objects/simple_test_vertex.py
  unittests/model_tests/application_graph_tests/test_application_vertex.py
Labels: enhancement

#330 Enable specific documenting of __call__() methods
  doc/doc_requirements.txt
  doc/source/conf.py
  doc/source/index.rst
  pacman/model/resources/abstract_sdram.py
  pacman/operations/__init__.py
  pacman/operations/algorithm_reports/__init__.py
  pacman/operations/algorithm_reports/network_specification.py
  pacman/operations/algorithm_reports/router_collision_potential_report.py
  pacman/operations/algorithm_reports/write_json_machine.py
  pacman/operations/algorithm_reports/write_json_machine_graph.py
  pacman/operations/algorithm_reports/write_json_partition_n_keys_map.py
  pacman/operations/algorithm_reports/write_json_placements.py
  pacman/operations/algorithm_reports/write_json_routing_tables.py
  pacman/operations/chip_id_allocator_algorithms/malloc_based_chip_id_allocator.py
  pacman/operations/fixed_route_router/fixed_route_router.py
  pacman/operations/partition_algorithms/basic_partitioner.py
  pacman/operations/partition_algorithms/partition_and_place_partitioner.py
  pacman/operations/placer_algorithms/connective_based_placer.py
  pacman/operations/placer_algorithms/one_to_one_placer.py
  pacman/operations/placer_algorithms/radial_placer.py
  pacman/operations/placer_algorithms/spreader_placer.py
  pacman/operations/rigged_algorithms/__init__.py
  pacman/operations/rigged_algorithms/hilbert_placer.py
  pacman/operations/rigged_algorithms/isomorph_check.py
  pacman/operations/rigged_algorithms/random_placer.py
  pacman/operations/router_algorithms/basic_dijkstra_routing.py
  pacman/operations/router_algorithms/ner_route.py
  pacman/operations/router_compressors/abstract_compressor.py
  pacman/operations/router_compressors/basic_route_merger.py
  pacman/operations/router_compressors/entry.py
  pacman/operations/router_compressors/mundys_router_compressor/__init__.py
  pacman/operations/router_compressors/mundys_router_compressor/ordered_covering.py
  pacman/operations/router_compressors/mundys_router_compressor/remove_default_routes.py
  pacman/operations/router_compressors/mundys_router_compressor/routing_table_condenser.py
  pacman/operations/router_compressors/pair_compressor.py
  pacman/operations/routing_info_allocator_algorithms/basic_routing_info_allocator.py
  pacman/operations/routing_info_allocator_algorithms/destination_based_key_allocator.py
  pacman/operations/routing_info_allocator_algorithms/field_based_routing_allocator/__init__.py
  pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/__init__.py
  pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/compressible_malloc_based_routing_info_allocator.py
  pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/malloc_based_routing_info_allocator.py
  pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
  pacman/operations/routing_table_generators/__init__.py
  pacman/operations/routing_table_generators/basic_routing_table_generator.py
  pacman/operations/routing_table_generators/zoned_routing_table_generator.py
  pacman/operations/tag_allocator_algorithms/basic_tag_allocator.py
  pacman/utilities/algorithm_utilities/machine_algorithm_utilities.py
  pacman/utilities/algorithm_utilities/partition_algorithm_utilities.py
  pacman/utilities/file_format_schemas/__init__.py
  pacman/utilities/json_utils.py
  pacman/utilities/utility_calls.py
  pacman/utilities/utility_objs/__init__.py
  pacman/utilities/utility_objs/resource_tracker.py
  pacman/utilities/vertex_sorter.py
Labels: enhancement, minor

#331 clone partitions when building new machine graphs
  pacman/model/graphs/application/application_graph.py
  pacman/model/graphs/machine/machine_graph.py
  pacman/model/graphs/outgoing_edge_partition.py
  unittests/model_tests/application_graph_tests/test_application_graph.py
  unittests/model_tests/machine_graph_tests/test_machine_graph_model.py
Labels: BLOCKER!, bug
