Repository SpiNNakerManchester/PACMAN, pull requests merged in 2020-02, with the labels that each got.

#276 Fix zoned allocator
  pacman/model/routing_info/base_key_and_mask.py
  pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
Labels: bug

#270 Reduce skipping
  pacman/operations/algorithms_metadata.xml
  pacman/operations/placer_algorithms/__init__.py
  pacman/operations/placer_algorithms/basic_placer.py
  uinit_test_objects/placer_test_support.py
  unittests/model_tests/application_graph_tests/test_application_vertex.py
  unittests/operations_tests/partition_algorithms_tests/test_partition_and_place_partitioner.py
  unittests/operations_tests/placer_algorithms_tests/test_basic_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_radial_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_virtual_placement.py
  unittests/operations_tests/router_algorithms_tests/test_basic_dijkstra_routing.py
  unittests/operations_tests/router_algorithms_tests/test_generic_router.py
Labels: enhancement

#279 makes things cleaner
  pacman/operations/algorithms_metadata.xml
  pacman/operations/multi_cast_router_check_functionality/valid_routes_checker.py
  pacman/operations/router_compressors/basic_route_merger.py
  pacman/operations/router_compressors/malloc_based_route_merger.py
  pacman/operations/router_compressors/mundys_router_compressor/ordered_covering.py
  pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
  pacman/utilities/constants.py
  unittests/model_tests/routing_info_tests/test_routing_info.py
Labels: enhancement, minor

#278 Json files
  pacman/executor/pacman_algorithm_executor.py
  pacman/model/routing_info/abstract_machine_partition_n_keys_map.py
  pacman/model/routing_info/dict_based_machine_partition_n_keys_map.py
  pacman/operations/algorithm_reports/reports_metadata.xml
  pacman/operations/algorithm_reports/write_json_machine.py
  pacman/operations/algorithm_reports/write_json_machine_graph.py
  pacman/operations/algorithm_reports/write_json_partition_n_keys_map.py
  pacman/operations/algorithm_reports/write_json_placements.py
  pacman/operations/algorithm_reports/write_json_routing_tables.py
  pacman/utilities/file_format_converters/__init__.py
  pacman/utilities/file_format_converters/converter_algorithms_metadata.xml
  pacman/utilities/file_format_schemas/machine.json
  pacman/utilities/file_format_schemas/machine_graph.json
  pacman/utilities/file_format_schemas/n_keys_map.json
  pacman/utilities/file_format_schemas/placements.json
  pacman/utilities/file_format_schemas/router.json
  pacman/utilities/file_format_schemas/routing_tables.json
  pacman/utilities/file_format_schemas/unused/routes.json
  pacman/utilities/file_format_schemas/unused/routing_keys.json
  pacman/utilities/file_format_schemas/unused/routing_tables.json
  pacman/utilities/file_format_schemas/unused/tag_allocations.json
  pacman/utilities/json_utils.py
  unittests/model_tests/routing_table_tests/test_routing_tables_model.py
Labels: enhancement

#281 Donals little fixes
  doc/source/.gitignore
  doc/source/conf.py
  pacman/executor/algorithm_metadata_xml_reader.py
  pacman/executor/injection_decorator.py
  pacman/executor/pacman_algorithm_executor.py
  pacman/executor/token_states.py
  pacman/model/constraints/partitioner_constraints/max_vertex_atoms_constraint.py
  pacman/model/constraints/partitioner_constraints/same_atoms_as_vertex_constraint.py
  pacman/model/decorators/__init__.py
  pacman/model/decorators/overrides.py
  pacman/model/graphs/common/constrained_object.py
  pacman/model/graphs/common/slice.py
  pacman/model/placements/placement.py
  pacman/model/placements/placements.py
  pacman/model/resources/constant_sdram.py
  pacman/model/resources/element_free_space.py
  pacman/model/resources/resource_container.py
  pacman/model/resources/specific_board_iptag_resource.py
  pacman/model/resources/variable_sdram.py
  pacman/model/routing_info/abstract_machine_partition_n_keys_map.py
  pacman/operations/fixed_route_router/fixed_route_router.py
  pacman/operations/placer_algorithms/one_to_one_placer.py
  pacman/operations/placer_algorithms/spreader_placer.py
  pacman/operations/router_compressors/basic_route_merger.py
  pacman/operations/router_compressors/clash_compressor.py
  pacman/operations/router_compressors/malloc_based_route_merger.py
  pacman/operations/router_compressors/mundys_router_compressor/ordered_covering.py
  pacman/operations/routing_table_generators/basic_routing_table_generator.py
  pacman/operations/tag_allocator_algorithms/basic_tag_allocator.py
  pacman/utilities/algorithm_utilities/element_allocator_algorithm.py
  pacman/utilities/vertex_sorter.py
  unittests/model_tests/algorithm_classes_tests/python_function_algorithm_tests.py
  unittests/model_tests/algorithm_classes_tests/test_python_class_algorithm.py
  unittests/model_tests/algorithm_classes_tests/test_python_function_algorithm.py
  unittests/model_tests/machine_graph_tests/test_machine_graph_model.py
  unittests/operations_tests/placer_algorithms_tests/test_same_chip_constraint.py
  unittests/operations_tests/placer_algorithms_tests/test_sdram_edge_placement.py
  unittests/test_algos.xml
  unittests/utilities_tests/test_report_states.py
  unittests/utilities_tests/test_reports.py
  unittests/utilities_tests/test_utility_calls.py
Labels: enhancement

#283 cherries from https://github.com/SpiNNakerManchester/PACMAN/pull/256
  pacman/model/constraints/key_allocator_constraints/fixed_key_field_constraint.py
  pacman/model/constraints/partitioner_constraints/fixed_vertex_atoms_constraint.py
Labels: enhancement

#284 Graph fixes
  pacman/model/graphs/__init__.py
  pacman/model/graphs/abstract_graph.py
  pacman/model/graphs/abstract_outgoing_edge_partition.py
  pacman/model/graphs/application/application_graph.py
  pacman/model/graphs/application/application_outgoing_edge_partition.py
  pacman/model/graphs/graph.py
  pacman/model/graphs/impl/__init__.py
  pacman/model/graphs/machine/machine_graph.py
  pacman/model/graphs/machine/machine_outgoing_edge_partition.py
  pacman/model/graphs/outgoing_edge_partition.py
  unittests/model_tests/routing_info_tests/test_routing_info.py
  unittests/model_tests/routing_table_tests/test_routing_tables_model.py
Labels: enhancement

#285 Doc fixes from files that also have graph mapper changes
  pacman/model/graphs/abstract_virtual.py
  pacman/model/graphs/application/application_edge.py
  pacman/model/graphs/application/application_graph.py
  pacman/model/graphs/application/application_vertex.py
  pacman/model/graphs/machine/machine_edge.py
  pacman/model/graphs/machine/machine_graph.py
  pacman/model/graphs/machine/machine_vertex.py
  pacman/operations/algorithm_reports/reports.py
  pacman/operations/algorithm_reports/write_json_machine.py
  pacman/operations/algorithm_reports/write_json_machine_graph.py
  pacman/operations/algorithm_reports/write_json_partition_n_keys_map.py
  pacman/operations/algorithm_reports/write_json_placements.py
  pacman/operations/algorithm_reports/write_json_routing_tables.py
  pacman/operations/multi_cast_router_check_functionality/valid_routes_checker.py
  pacman/operations/partition_algorithms/basic_partitioner.py
  pacman/operations/partition_algorithms/partition_and_place_partitioner.py
  pacman/operations/router_compressors/mundys_router_compressor/routing_table_condenser.py
  pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/malloc_based_routing_info_allocator.py
  pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
  pacman/operations/routing_table_generators/zoned_routing_table_generator.py
  pacman/utilities/algorithm_utilities/partition_algorithm_utilities.py
  pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
  unittests/operations_tests/partition_algorithms_tests/test_basic_partitioner.py
  unittests/operations_tests/partition_algorithms_tests/test_partition_and_place_partitioner.py
Labels: enhancement, minor
