Repository SpiNNakerManchester/PACMAN, pull requests merged in 2020-10, with the labels that each got.

#307 Stop edges being added twice
  pacman/model/graphs/graph.py
  unittests/model_tests/machine_graph_tests/test_machine_graph_model.py
  unittests/operations_tests/placer_algorithms_tests/test_connecitve_placer.py
Labels: BLOCKER!

#314 Json edge label optional
  pacman/utilities/file_format_schemas/machine_graph.json
  unittests/utilities_tests/test_json_utils.py
Labels: enhancement

#312 all or nothing for machinevertex.appvertex
  pacman/model/graphs/machine/machine_graph.py
  unittests/model_tests/machine_graph_tests/test_machine_graph_model.py
Labels: minor

#311 ZoneKeyAllocator fixes
  pacman/model/graphs/machine/machine_graph.py
  pacman/operations/algorithms_metadata.xml
  pacman/operations/routing_info_allocator_algorithms/__init__.py
  pacman/operations/routing_info_allocator_algorithms/global_zoned_routing_info_allocator.py
  pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/compressible_malloc_based_routing_info_allocator.py
  pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/malloc_based_routing_info_allocator.py
  pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
  pacman/utilities/json_utils.py
  pacman/utilities/utility_calls.py
  unittests/operations_tests/routing_info_algorithms_tests/test_global_zoned_routing_allocator.py
  unittests/operations_tests/routing_info_algorithms_tests/test_zoned_routing_allocator.py
Labels: enhancement

#321 convert numpy integer to int
  pacman/model/resources/constant_sdram.py
  pacman/model/resources/cpu_cycles_per_tick_resource.py
  pacman/model/resources/dtcm_resource.py
  pacman/model/resources/multi_region_sdram.py
  pacman/model/resources/variable_sdram.py
Labels: enhancement

#322 Allow variable SDRAM to be a float
  pacman/model/resources/variable_sdram.py
Labels: bug
