Repository SpiNNakerManchester/PACMAN, pull requests merged in 2021-02, with the labels that each got.

#343 Repair SDRAM Allocation
  pacman/model/partitioner_splitters/abstract_splitters/abstract_splitter_slice.py
  pacman/operations/partition_algorithms/splitter_partitioner.py
  pacman/utilities/algorithm_utilities/placer_algorithm_utilities.py
  pacman/utilities/utility_objs/resource_tracker.py
Labels: bug

#353 added some docs
  pacman/operations/router_compressors/clash_compressor.py
Labels: minor

#354 Test 3 9
  .github/workflows/python_actions.yml
  doc/source/conf.py
  setup.py
Labels: enhancement

#355 remove leftover six references
  .pylintrc
  README.md
  doc/doc_requirements.txt
  requirements.txt
Labels: bug, minor

#357 Write sphinx config right
  doc/source/conf.py
Labels: BLOCKER!, bug

#356 Lost spike issues
  pacman/operations/router_algorithms/ner_route.py
  unittests/operations_tests/router_algorithms_tests/test_ner_route_default.py
Labels: bug, enhancement
