Repository SpiNNakerManchester/PACMAN, pull requests merged in 2021-01, with the labels that each got.

#341 log warning to file
  pacman/executor/algorithm_decorators/algorithm_decorator.py
  pacman/operations/chip_id_allocator_algorithms/malloc_based_chip_id_allocator.py
  pacman/operations/placer_algorithms/connective_based_placer.py
  pacman/operations/placer_algorithms/radial_placer.py
  pacman/operations/rigged_algorithms/hilbert_placer.py
  pacman/operations/router_algorithms/basic_dijkstra_routing.py
  pacman/operations/router_compressors/abstract_compressor.py
  pacman/utilities/algorithm_utilities/routing_info_allocator_utilities.py
Labels: enhancement

#346 sortedcollections needs version restriction for Python 2.7
  requirements.txt
  setup.py
Labels: BLOCKER!, bug

#347 Several minor fixes to Compressors
  pacman/operations/algorithms_metadata.xml
  pacman/operations/router_compressors/__init__.py
  pacman/operations/router_compressors/checked_unordered_pair_compressor.py
  pacman/operations/router_compressors/ordered_covering_router_compressor/__init__.py
  pacman/operations/router_compressors/ordered_covering_router_compressor/ordered_covering.py
  pacman/operations/router_compressors/ordered_covering_router_compressor/ordered_covering_compressor.py
  pacman/operations/router_compressors/ordered_covering_router_compressor/remove_default_routes.py
  pacman/operations/router_compressors/ordered_covering_router_compressor/utils.py
  pacman/operations/router_compressors/unordered_pair_compressor.py
  unittests/operations_tests/router_compressor_tests/test_compressors.py
Labels: enhancement

#348 Fix to print strings correctly, make messages more specific
  pacman/executor/algorithm_decorators/algorithm_decorator.py
Labels: bug, minor

#350 zoned with no or only fixed edges only
  pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
  unittests/operations_tests/routing_info_algorithms_tests/test_zoned_routing_allocator.py
Labels: bug

#351 fixy fixy
  pacman/operations/placer_algorithms/spreader_placer.py
Labels: bug, enhancement
