Repository SpiNNakerManchester/PACMAN, pull requests merged in 2021-06, with the labels that each got.

#384 Update compressor tests
  pacman/operations/router_compressors/basic_route_merger.py
  pacman/operations/router_compressors/malloc_based_route_merger.py
  pacman_integration_tests/manual_runner.py
  pacman_integration_tests/test_big_compression.py
  unittests/operations_tests/router_compressor_tests/many_to_one.json.gz
  unittests/operations_tests/router_compressor_tests/test_checked_unordered_pair_compression.py
  unittests/operations_tests/router_compressor_tests/test_ordered_covering_compression.py
  unittests/operations_tests/router_compressor_tests/test_pair_compression.py
  unittests/operations_tests/router_compressor_tests/test_unordered_pair_compression.py
Labels: enhancement

#385 Exceptions cleanup
  pacman/exceptions.py
  pacman/operations/router_compressors/ordered_covering_router_compressor/ordered_covering.py
  pacman/operations/router_compressors/ordered_covering_router_compressor/remove_default_routes.py
Labels: bug, enhancement

#364 Test objects
  pacman/model/graphs/machine/machine_vertex.py
  pacman/model/graphs/machine/simple_machine_vertex.py
  pacman_test_objects/__init__.py
  pacman_test_objects/duck_legacy_app_vertex.py
  pacman_test_objects/mock_machine_vertex.py
  pacman_test_objects/non_legacy_app_vertex.py
  pacman_test_objects/placer_test_support.py
  pacman_test_objects/simple_test_edge.py
  pacman_test_objects/simple_test_partitioning_constraint.py
  pacman_test_objects/simple_test_vertex.py
  uinit_test_objects/placer_test_support.py
  unittests/model_tests/application_graph_tests/test_application_edge.py
  unittests/model_tests/application_graph_tests/test_application_graph.py
  unittests/model_tests/application_graph_tests/test_application_vertex.py
  unittests/model_tests/graph_mapper_tests/test_graph_mapping.py
  unittests/model_tests/machine_graph_tests/test_machine_graph_model.py
  unittests/model_tests/partitioner_splitters_tests/splitter_slice_legacy_test.py
  unittests/model_tests/splitter_tests/test_one_app_one_machine.py
  unittests/model_tests/splitter_tests/test_splitter_slice_legacy.py
  unittests/operations_tests/partition_algorithms_tests/test_basic_partitioner.py
  unittests/operations_tests/partition_algorithms_tests/test_partitioner.py
  unittests/operations_tests/partition_algorithms_tests/test_partitioner_with_pre_allocated_resources.py
  unittests/operations_tests/partition_algorithms_tests/test_splitter_partitioner.py
  unittests/operations_tests/placer_algorithms_tests/test_connecitve_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_one_to_one_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_radial_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_sdram_edge_placement.py
  unittests/operations_tests/placer_algorithms_tests/test_spreader_placer.py
  unittests/operations_tests/routing_info_algorithms_tests/test_zoned_routing_allocator.py
Labels: enhancement

#389 Remove unused algorithms
  pacman/operations/algorithms_metadata.xml
  pacman/operations/rigged_algorithms/__init__.py
  pacman/operations/rigged_algorithms/hilbert_placer.py
  pacman/operations/rigged_algorithms/hilbert_state.py
  pacman/operations/rigged_algorithms/random_placer.py
  pacman/operations/routing_info_allocator_algorithms/__init__.py
  pacman/operations/routing_info_allocator_algorithms/basic_routing_info_allocator.py
Labels: minor

#388 Graph view
  pacman/model/graphs/application/__init__.py
  pacman/model/graphs/application/application_graph.py
  pacman/model/graphs/application/application_graph_view.py
  pacman/model/graphs/machine/__init__.py
  pacman/model/graphs/machine/machine_graph.py
  pacman/model/graphs/machine/machine_graph_view.py
  unittests/model_tests/application_graph_tests/test_application_graph.py
  unittests/model_tests/machine_graph_tests/test_machine_graph_model.py
Labels: bug

#381 Stop passing config values through the simulator
  pacman/operations/algorithms_metadata.xml
  pacman/operations/router_compressors/abstract_compressor.py
  pacman/operations/router_compressors/checked_unordered_pair_compressor.py
  pacman/operations/router_compressors/ordered_covering_router_compressor/ordered_covering.py
  pacman/operations/router_compressors/ordered_covering_router_compressor/ordered_covering_compressor.py
  unittests/operations_tests/partition_algorithms_tests/test_basic_partitioner.py
  unittests/operations_tests/partition_algorithms_tests/test_partitioner.py
  unittests/operations_tests/partition_algorithms_tests/test_partitioner_with_pre_allocated_resources.py
  unittests/operations_tests/placer_algorithms_tests/test_connecitve_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_one_to_one_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_radial_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_same_chip_constraint.py
  unittests/operations_tests/placer_algorithms_tests/test_sdram_edge_placement.py
  unittests/operations_tests/placer_algorithms_tests/test_spreader_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_virtual_placement.py
  unittests/operations_tests/router_algorithms_tests/test_basic_dijkstra_routing.py
  unittests/operations_tests/router_algorithms_tests/test_ner_route_default.py
  unittests/operations_tests/router_algorithms_tests/test_ner_route_traffic_aware.py
  unittests/operations_tests/router_compressor_tests/test_compressors.py
  unittests/operations_tests/tag_allocator_tests/test_tags_board_addresses.py
  unittests/test_cfg_checker.py
  unittests/test_fixed_route_router.py
  unittests/test_pacman_algorithm_executor.py
  unittests/utilities_tests/test_resource_tracker.py
Labels: enhancement

#392 reset_configs
  unittests/operations_tests/router_compressor_tests/test_checked_unordered_pair_compression.py
  unittests/operations_tests/router_compressor_tests/test_ordered_covering_compression.py
  unittests/operations_tests/router_compressor_tests/test_pair_compression.py
  unittests/operations_tests/router_compressor_tests/test_unordered_pair_compression.py
Labels: blocker

#393 Unittest setup
  pacman/config_setup.py
  pacman_integration_tests/test_big_compression.py
  unittests/model_tests/algorithm_classes_tests/test_python_class_algorithm.py
  unittests/model_tests/algorithm_classes_tests/test_python_function_algorithm.py
  unittests/model_tests/application_graph_tests/test_application_edge.py
  unittests/model_tests/application_graph_tests/test_application_graph.py
  unittests/model_tests/application_graph_tests/test_application_vertex.py
  unittests/model_tests/graph_mapper_tests/test_graph_mapping.py
  unittests/model_tests/graph_mapper_tests/test_slice.py
  unittests/model_tests/machine_graph_tests/test_machine_graph_model.py
  unittests/model_tests/partitioner_splitters_tests/splitter_slice_legacy_test.py
  unittests/model_tests/placement_tests/test_placement_constraints.py
  unittests/model_tests/placement_tests/test_placement_object.py
  unittests/model_tests/placement_tests/test_placements_model.py
  unittests/model_tests/resources_tests/test_resources_model.py
  unittests/model_tests/routing_info_tests/test_routing_info.py
  unittests/model_tests/routing_table_tests/test_routing_tables_model.py
  unittests/model_tests/splitter_tests/test_one_app_one_machine.py
  unittests/model_tests/splitter_tests/test_splitter_slice_legacy.py
  unittests/model_tests/tag_tests/test_tag_infos_model.py
  unittests/model_tests/test_key_allocator.py
  unittests/model_tests/test_partition.py
  unittests/model_tests/test_slice.py
  unittests/operations_tests/partition_algorithms_tests/test_basic_partitioner.py
  unittests/operations_tests/partition_algorithms_tests/test_partitioner.py
  unittests/operations_tests/partition_algorithms_tests/test_partitioner_with_pre_allocated_resources.py
  unittests/operations_tests/partition_algorithms_tests/test_splitter_partitioner.py
  unittests/operations_tests/placer_algorithms_tests/test_connecitve_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_one_to_one_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_radial_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_same_chip_constraint.py
  unittests/operations_tests/placer_algorithms_tests/test_sdram_edge_placement.py
  unittests/operations_tests/placer_algorithms_tests/test_spreader_placer.py
  unittests/operations_tests/placer_algorithms_tests/test_virtual_placement.py
  unittests/operations_tests/router_algorithms_tests/test_basic_dijkstra_routing.py
  unittests/operations_tests/router_algorithms_tests/test_ner_route_default.py
  unittests/operations_tests/router_algorithms_tests/test_ner_route_traffic_aware.py
  unittests/operations_tests/router_compressor_tests/test_checked_unordered_pair_compression.py
  unittests/operations_tests/router_compressor_tests/test_compressors.py
  unittests/operations_tests/router_compressor_tests/test_ordered_covering_compression.py
  unittests/operations_tests/router_compressor_tests/test_pair_compression.py
  unittests/operations_tests/router_compressor_tests/test_unordered_pair_compression.py
  unittests/operations_tests/routing_info_algorithms_tests/test_malloc_routing_info_allocator.py
  unittests/operations_tests/routing_info_algorithms_tests/test_mask_generator.py
  unittests/operations_tests/routing_info_algorithms_tests/test_zoned_routing_allocator.py
  unittests/operations_tests/tag_allocator_tests/test_tags_board_addresses.py
  unittests/test_cfg_checker.py
  unittests/test_fixed_route_router.py
  unittests/test_import_all.py
  unittests/test_pacman_algorithm_executor.py
  unittests/test_token_states.py
  unittests/test_version.py
  unittests/utilities_tests/test_constants.py
  unittests/utilities_tests/test_json_utils.py
  unittests/utilities_tests/test_placer_algorithm_utilities.py
  unittests/utilities_tests/test_resource_tracker.py
Labels: enhancement

#391 report directories as global_variables
  pacman/operations/algorithms_metadata.xml
  pacman/operations/router_compressors/routing_compression_checker.py
  pacman_integration_tests/manual_runner.py
Labels: enhancement

#390 Bye bye outer_table_compression_target_length setting
  pacman/operations/router_compressors/abstract_compressor.py
  pacman/operations/router_compressors/checked_unordered_pair_compressor.py
  pacman/operations/router_compressors/ordered_covering_router_compressor/ordered_covering.py
  pacman/operations/router_compressors/pair_compressor.py
  pacman/pacman.cfg
  pacman_integration_tests/manual_runner.py
  pacman_integration_tests/test_big_compression.py
  unittests/operations_tests/router_compressor_tests/test_checked_unordered_pair_compression.py
  unittests/operations_tests/router_compressor_tests/test_compressors.py
Labels: minor

#396 Split synapse neuron models
  pacman/model/partitioner_splitters/splitter_reset.py
  pacman/operations/algorithms_metadata.xml
  pacman/operations/placer_algorithms/one_to_one_placer.py
  pacman/utilities/utility_objs/resource_tracker.py
Labels: bug, enhancement
