Repository SpiNNakerManchester/PACMAN, pull requests merged in 2021-03, with the labels that each got.

#358 Split out the list of files to put in documentation
  doc/source/conf.py
  doc/unfiltered-files.txt
Labels: enhancement, minor

#359 use get_existing_xys_by_ethernet as you just want xy
  pacman/utilities/utility_objs/resource_tracker.py
Labels: enhancement

#363 removed compressor that did not and does not work
  pacman/operations/router_compressors/clash_compressor.py
Labels: minor
