Repository SpiNNakerManchester/PACMAN, pull requests merged in 2021-04, with the labels that each got.

#365 Bump6.0.1
  doc/source/conf.py
  pacman/_version.py
  requirements.txt
  setup.py
Labels: next_release

#366 nuked CompressibleMallocBasedRoutingInfoAllocator
  pacman/operations/algorithms_metadata.xml
  pacman/operations/routing_info_allocator_algorithms/__init__.py
  pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/__init__.py
  pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/compressible_malloc_based_routing_info_allocator.py
Labels: bug

#367 nuked DestinationBasedRoutingInfoAllocator
  pacman/operations/algorithms_metadata.xml
  pacman/operations/routing_info_allocator_algorithms/__init__.py
  pacman/operations/routing_info_allocator_algorithms/destination_based_key_allocator.py
Labels: minor

#368 Nuke IsomorphicChecker
  pacman/operations/algorithms_metadata.xml
  pacman/operations/rigged_algorithms/__init__.py
  pacman/operations/rigged_algorithms/isomorph_check.py
Labels: minor

#369 Tags passed as Tags object only
  pacman/operations/algorithms_metadata.xml
  pacman/operations/tag_allocator_algorithms/basic_tag_allocator.py
  unittests/operations_tests/tag_allocator_tests/test_tags_board_addresses.py
Labels: enhancement

#371 Making the configs truly global
  pacman/config_holder.py
  pacman/spinnaker.cfg
  pacman/spinnaker.cfg.template
Labels: enhancement

#372 Removing additional item removed in another merge to FEC
  pacman/spinnaker.cfg
Labels: bug

#376 Config checker
  pacman/config_holder.py
  pacman/spinnaker.cfg
  unittests/test_cfg_checker.py
Labels: enhancement

#377 Router max entries from Machine
  pacman/spinnaker.cfg
Labels: enhancement

#378 Cfg stack
  pacman/config_holder.py
  pacman/config_setup.py
  pacman/pacman.cfg
  pacman/spinnaker.cfg
  pacman/spinnaker.cfg.template
  unittests/test_cfg_checker.py
Labels: enhancement
