Repository SpiNNakerManchester/PACMAN, pull requests merged in 2023-04, with the labels that each got.

#510 Improve github integration
  .github/dependabot.yml
  .github/workflows/python_actions.yml
Labels: bug, minor

#511 Clean up of splitter code
  pacman/data/pacman_data_view.py
  pacman/data/pacman_data_writer.py
  pacman/exceptions.py
  pacman/model/graphs/application/application_vertex.py
  pacman/model/partitioner_interfaces/__init__.py
  pacman/model/partitioner_interfaces/abstract_splitter_partitioner.py
  pacman/model/partitioner_interfaces/legacy_partitioner_api.py
  pacman/model/partitioner_splitters/__init__.py
  pacman/model/partitioner_splitters/abstract_splitter_common.py
  pacman/model/partitioner_splitters/abstract_splitters/__init__.py
  pacman/model/partitioner_splitters/splitter_external_device.py
  pacman/model/partitioner_splitters/splitter_fixed_legacy.py
  pacman/model/partitioner_splitters/splitter_one_app_one_machine.py
  pacman/model/partitioner_splitters/splitter_one_to_one_legacy.py
  pacman/operations/partition_algorithms/splitter_partitioner.py
  pacman/operations/placer_algorithms/application_placer.py
  pacman_test_objects/simple_test_vertex.py
  setup.cfg
  unittests/operations_tests/placer_algorithms_tests/test_application_placer.py
  unittests/operations_tests/router_algorithms_tests/test_routers.py
  unittests/operations_tests/routing_info_algorithms_tests/test_zoned_routing_allocator.py
Labels: minor

#498 Cache atoms shape
  pacman/model/graphs/application/abstract/abstract_2d_device_vertex.py
  pacman/model/graphs/common/__init__.py
  pacman/model/graphs/common/mdslice.py
  pacman/model/graphs/common/slice.py
  pacman/utilities/algorithm_utilities/partition_algorithm_utilities.py
  unittests/model_tests/test_mdslice.py
  unittests/model_tests/test_slice.py
Labels: enhancement
