Repository SpiNNakerManchester/PACMAN, pull requests merged in 2023-02, with the labels that each got.

#485 fix raise Exception
  pacman/model/graphs/abstract_multiple_partition.py
  pacman/model/graphs/common/slice.py
  pacman/model/routing_table_by_partition/multicast_routing_table_by_partition_entry.py
  pacman/operations/multi_cast_router_check_functionality/valid_routes_checker.py
  pacman/operations/router_algorithms/application_router.py
  pacman/operations/router_compressors/pair_compressor.py
  pacman/operations/routing_table_generators/merged_routing_table_generator.py
  unittests/operations_tests/router_algorithms_tests/test_routers.py
  unittests/operations_tests/routing_table_generator_tests/test_merged.py
Labels: blocker

#486 Move bits_needed function into utility_calls
  pacman/operations/routing_info_allocator_algorithms/zoned_routing_info_allocator.py
  pacman/utilities/utility_calls.py
Labels: bug

#491 Fix pool dense
  pacman/model/graphs/application/abstract/abstract_2d_device_vertex.py
  pacman/model/partitioner_splitters/splitter_external_device.py
  pacman/operations/placer_algorithms/application_placer.py
  pacman/operations/router_algorithms/application_router.py
  pacman/pacman.cfg
  unittests/operations_tests/router_algorithms_tests/test_routers.py
Labels: bug, enhancement
